language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
    - jags
os:
- linux
- osx
osx_image: xcode9.4
services:
- xvfb
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=oslerinhealth
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- if [ "${codename}" = "trusty" ]; then start_xvfb ; fi
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install || true;
- v8_install || true;
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- install_python_requirements ;
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: Maz62tpLDpdb2qSzZjl1WFlz8w0+Ims0kgQOHMkqtnaByItG7cRScRcn13e4Wx9rZmBhShahq0bWinU29C6nIULbPw6j+NtIECsTU47Fun4ufvBVor8rSKbhuVRqmBtzAg5zYALTeH89VaFTdWJ1y8xYeX3s0CmvZF61Ratyc2duROkLfmKptD5atPQeVBeTPitMBb1BqBcJz4f7HkApHOePnd7cRjKc3scG4e8nahlPmPZl5j/WtOljS6fmZjewwfZwfsQkzrcjBX7cp/m6OJeVdGlMCWh0AiWDquzuAcfIQfYWDtAIwq7FjllepjrRDK55rSi2bgnc0beut4x/+H2TpatHTGFau1HFNE2s3S/6qbpa8T3KBrYqTLAu1bB/W0fQGgZ74Vdxt0Phqhi8KvA4SPSun3ihE6aWVhzz2OLwrzlXT8096NPeIeATbTvLDd0O9eF5P/0sFvGYZ/UHgUtjbO0FpcLiMZBuZqAVGMAotR7Isgvve8V2Oqq8tBIT62GvYthDks9dn3xdSj7og0tORpvdULHqVFZ4ICIDBGYx4rHHd9POdcHkCTapRQHc8jgzfpn2QAAyqBB+XO5KO+R01llsU3RO5AsrpS9rMO14d7v6ciAqQ47dtQW+WPjhz/h7f8xV2dqUcwyIagcbfZewZp2QUZIyJN1GqxI2Mao=
after_deploy:
- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
  else run_coverage=; fi;
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" &&
  -z "${run_coverage}" ]]; then echo 'covr::coveralls(type = "all", quiet = FALSE)'
  > osler_covr.R ; travis_wait 100 Rscript osler_covr.R ; rm osler_covr.R ; fi

#neuroc.deps version (SHA): a5aa5ca