language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
    - jags
os:
- linux
- osx
osx_image: xcode9.4
services:
- xvfb
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=oslerinhealth
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- if [ "${codename}" = "trusty" ]; then start_xvfb ; fi
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install || true;
- v8_install || true;
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- install_python_requirements ;
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: P3XqJyiY0ub9/kZQrqaoTajXQzNHi9WxMwiu1mrZaukIikloWwHoar45OsJKhSANq8/TxN8Rc7KadcFs7mMLMzzszjUc//uqOeubU4/qpM8bVYf9cIb6LF0vpkkY3dEo0Al3UwkqkET83izG9kOr1CN0ZqSMAUgMbW9Rkv83fCOBZFENk5qSHgF2y5+3Ry6SvMRZUsKrHcnVmiYVg+6OB3U7yb1zDAris1aXfGgCtRtztC2t7XfKCLtVE7vJb+moHpJ0XkQdkypx0fe6BJCmLhUSNTRXSlVYTBJYMFVEwkw6DdZie2fNU+F78w1T9EJc3D1rS82Nsfm/rU7pSULiZLl/eqeIjM1aT98DlZ2+/ioxdMZ+hWyOhSGreXfUGVgpxnz6ZgUNF5j9m1NPloPgKxOok7v2TKDbpViYOMLnrcOLCYmoF2UXF6DYz9Zs4beo47MxgtPXIxqG8PNnAUcZMJFbLvXb8i6eOg7o+PXC0Ifg2bnlhr6ZlFDgaVgTcfNEnbbewwf+yURAPc+y97rzulO7lYkAzkNpLn7penOusa8fIOCeZPknDFPczNcLGY8rMcyjWDmgtIJ7K9VMzWFdnQ1Ggp5zVGoKeuLPonfqJN2v/SSIHGE/np/uLx8chKp1cHFw5YOXWvyV97pEy5FOR+vB5+sEqdwUl6C3PZxx4mI=
after_deploy:
- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
  else run_coverage=; fi;
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" &&
  -z "${run_coverage}" ]]; then echo 'covr::coveralls(type = "all", quiet = FALSE)'
  > osler_covr.R ; travis_wait 100 Rscript osler_covr.R ; rm osler_covr.R ; fi

#neuroc.deps version (SHA): a5aa5ca